// 贝克兰德内容包：角色创建默认值与随机人物模板。
export const DEFAULT_CHARACTER = {
  name: "",
  gender: "女",
  age: 24,
  avatar: "",
  appearance: "",
  origin: "贝克兰德桥区",
  startingDistrict: "东区",
  clothingDescription: "旧呢外套、白衬衫、黑长裤、磨损的皮靴",
  carriedItemName: "",
  carriedItemDescription: "",
  occupation: "报社校对员",
  personality: "谨慎、敏锐，对权威保留怀疑",
  desire: "找到足以改变自己命运的真相",
  fear: "在不知情时成为某种仪式的一部分",
  secret: "曾从一封无人认领的遗书上抄下异常符号",
  background: "在贝克兰德生活三年，靠处理夜班稿件维持体面的贫穷。",
  extraordinary: "ordinary",
  pathway: "无",
  talent: "none",
  startingMoneyPence: 240,
};

export const RANDOM_CHARACTERS = [
  {
    name: "伊芙琳·沃德",
    gender: "女",
    age: 26,
    appearance: "深褐短发，灰绿色眼睛，常穿改窄的旧旅行外套。",
    origin: "间海郡",
    occupation: "私人信件抄写员",
    personality: "冷静、好奇，习惯记录细节",
    desire: "证明父亲留下的航海日志并非疯话",
    fear: "镜中的自己比现实慢半拍",
    secret: "她能偶尔听见旧物主人残留的低语",
    background: "替桥区商人誊写账目与私人函件，熟悉贝克兰德不同阶层的说话方式。",
    extraordinary: "low",
    pathway: "窥秘人（序列9）",
  },
  {
    name: "西奥多·兰恩",
    gender: "男",
    age: 31,
    appearance: "瘦高，金边眼镜后有一双睡眠不足的蓝眼睛。",
    origin: "东切斯特郡",
    occupation: "保险调查员",
    personality: "礼貌、固执，对数字异常极其敏感",
    desire: "攒够钱离开终年笼罩煤烟的贝克兰德",
    fear: "无法解释的巧合",
    secret: "三年前曾伪造一次火灾勘验结果",
    background: "受雇调查货栈损失，凭职业便利出入码头、警署与商会。",
    extraordinary: "ordinary",
    pathway: "无",
  },
  {
    name: "诺拉·贝尔",
    gender: "女",
    age: 22,
    appearance: "黑卷发束在脑后，左手虎口有淡白色灼痕。",
    origin: "贝克兰德桥区·旧钟街",
    occupation: "钟表匠学徒",
    personality: "直率、耐心，对机械声有近乎苛刻的记忆",
    desire: "拥有一间不受行会控制的修表铺",
    fear: "密闭且完全安静的房间",
    secret: "她修好的一只怀表会在有人撒谎时停摆",
    background: "在煤烟巷的钟表铺长大，认识巡夜人、典当商和大多数跑腿孩子。",
    extraordinary: "ordinary",
    pathway: "无",
  },
];

