import { SIDE_QUEST_DEFINITIONS } from "./sideQuests.js";
import { WATCH_DISCOVERY_QUESTS, WATCH_MAIN_QUESTS } from "./watch.js";

export const SPECIAL_QUEST_DEFINITIONS = [
  ...WATCH_DISCOVERY_QUESTS,
  ...WATCH_MAIN_QUESTS,
  ...SIDE_QUEST_DEFINITIONS,
];
